version: "3.7"

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app_pass
    networks:
      - app_net


  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6378:6379
    networks:
      - app_net


  php:
    container_name: php
    build:
      context: .
      target: php
    env_file: './.env.docker'
    links:
      - redis
      - postgres
    volumes:
     - ./:/var/www/html/
    networks:
      - app_net


  php_worker:
    container_name: php_worker
    build:
      context: .
      target: php_worker
    links:
      - redis
      - postgres
    restart: always
    volumes:
      - ./docker/supervisor/queue.conf:/etc/supervisor/queue.conf
      - ./:/var/www/html/
    networks:
      - app_net


  nginx:
    container_name: nginx
    build:
      context: .
      target: nginx
    links:
      - php
    ports:
      - 8010:80
    networks:
      - app_net
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public


networks:
  app_net:
    driver: bridge


volumes:
  pgdata:
    driver: local
